# id: 1
server:
  address: "server:12345"
loop:
  lapse: "0m20s"
  period: "5s"
log:
  level: "info"
bet:
  nombre: "Santiago Lionel去"
  apellido: "Lorca"
  documento: "30904465"
  nacimiento: "1999-03-17"
  numero: "7574"
